apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-env
  template:
    metadata:
      labels:
        app: k8s-env
    spec:
      volumes:
        - name: tempvol
          emptyDir: {}
      containers:
        - name: k8s-env
          image: pythonincontainers/k8s-env:v1.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: tempvol
              mountPath: /tmp-vol
